universe = docker
docker_image = xtang75/bnn-software:2
log = ../log/soil_disease/bnn_$(Cluster)_$(Process).log

executable = soil_disease.sh
arguments = $(file)
output = ../output/soil_disease/bnn_$(Cluster)_$(Process).out
error = ../error/soil_disease/bnn_$(Cluster)_$(Process).err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = chem.txt,soil_disease.sh,../data/soil_disease/

requirements = (OpSysMajorVer == 8) && (Machine =!= "e2487.chtc.wisc.edu")
request_cpus = 1
request_memory = 200MB
request_disk = 20GB

queue file from chem.txt
