universe = docker
docker_image = xtang75/bnn-software:2
log = ../log/otu_soil/class/bnn_$(Cluster)_$(Process).log

executable = class_pctg.sh
arguments = $(file)
output = ../output/otu_soil/class/bnn_$(Cluster)_$(Process).out
error = ../error/otu_soil/class/bnn_$(Cluster)_$(Process).err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = pctg.txt,class_pctg.sh,../data/otu_soil/class/

requirements = (OpSysMajorVer == 8) && (Machine =!= "e2487.chtc.wisc.edu")
request_cpus = 1
request_memory = 200MB
request_disk = 40GB

queue file from pctg.txt
