universe = docker
docker_image = xtang75/bnn-software:2
log = ../log/otu_soil/family/bnn_$(Cluster)_$(Process).log

executable = family_scabpit.sh
arguments = $(file)
output = ../output/otu_soil/family/bnn_$(Cluster)_$(Process).out
error = ../error/otu_soil/family/bnn_$(Cluster)_$(Process).err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = scabpit.txt,family_scabpit.sh,../data/otu_soil/family/

requirements = (OpSysMajorVer == 8) && (Machine =!= "e2487.chtc.wisc.edu")
request_cpus = 1
request_memory = 300MB
request_disk = 40GB

queue file from scabpit.txt
