universe = docker
docker_image = xtang75/bnn-software:2
log = ../log/chemistry/bnn_$(Cluster)_$(Process).log

executable = chem_nn.sh
arguments = $(file)
output = ../output/chemistry/bnn_$(Cluster)_$(Process).out
error = ../error/chemistry/bnn_$(Cluster)_$(Process).err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = chem.txt,chem_nn.sh,../data/chemistry/

requirements = (OpSysMajorVer == 8) && (Machine =!= "e2487.chtc.wisc.edu")
request_cpus = 1
request_memory = 300MB
request_disk = 30GB

queue file from chem.txt
