universe = docker
docker_image = xtang75/bnn-software:2
log = ../log/alpha_soil/genus/bnn_$(Cluster)_$(Process).log

executable = genus.sh
arguments = $(file)
output = ../output/alpha_soil/genus/bnn_$(Cluster)_$(Process).out
error = ../error/alpha_soil/genus/bnn_$(Cluster)_$(Process).err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = filename.txt,genus.sh,../data/alpha_soil/genus/

requirements = (OpSysMajorVer == 8) && (Machine =!= "e2487.chtc.wisc.edu")
request_cpus = 1
request_memory = 300MB
request_disk = 30GB

queue file from filename.txt
