universe = docker
docker_image = xtang75/bnn-software:2
log = ../log/all_otu_augumented/order/bnn_$(Cluster)_$(Process).log

executable = order.sh
arguments = $(file)
output = ../output/all_otu_augumented/order/bnn_$(Cluster)_$(Process).out
error = ../error/all_otu_augumented/order/bnn_$(Cluster)_$(Process).err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = filename.txt,order.sh,../data/all_otu_augumented/order/

requirements = (OpSysMajorVer == 8) && (Machine =!= "e2487.chtc.wisc.edu")
request_cpus = 1
request_memory = 200MB
request_disk = 40GB

queue file from filename.txt
