universe = docker
docker_image = xtang75/bnn-software:2
log = ../log/otu_soil_disease/genus/bnn_$(Cluster)_$(Process).log

executable = genus_meter.sh
arguments = $(file)
output = ../output/otu_soil_disease/genus/bnn_$(Cluster)_$(Process).out
error = ../error/otu_soil_disease/genus/bnn_$(Cluster)_$(Process).err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = meter.txt,genus_meter.sh,../data/otu_soil_disease/genus/

requirements = (OpSysMajorVer == 8) && (Machine =!= "e2487.chtc.wisc.edu")
request_cpus = 1
request_memory = 400MB
request_disk = 80GB

queue file from meter.txt
