universe = docker
docker_image = xtang75/bnn-software:2
log = ../log/otu_1/phylum/bnn_$(Cluster)_$(Process).log

executable = phylum_meter.sh
arguments = $(file)
output = ../output/otu_1/phylum/bnn_$(Cluster)_$(Process).out
error = ../error/otu_1/phylum/bnn_$(Cluster)_$(Process).err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = meter.txt,phylum_meter.sh,../data/otu_1/phylum/

requirements = (OpSysMajorVer == 8) && (Machine =!= "e2487.chtc.wisc.edu")
request_cpus = 1
request_memory = 200MB
request_disk = 40GB

queue file from meter.txt
