universe = docker
docker_image = xtang75/bnn-software:2
log = ../log/otu_1/class/bnn_$(Cluster)_$(Process).log

executable = class_plant.sh
arguments = $(file)
output = ../output/otu_1/class/bnn_$(Cluster)_$(Process).out
error = ../error/otu_1/class/bnn_$(Cluster)_$(Process).err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = plant.txt,class_plant.sh,../data/otu_1/class/

requirements = (OpSysMajorVer == 8) && (Machine =!= "e2487.chtc.wisc.edu")
request_cpus = 1
request_memory = 500MB
request_disk = 100GB

queue file from plant.txt
