universe = docker
docker_image = xtang75/bnn-software:2
log = ../log/otu_1/genus/bnn_$(Cluster)_$(Process).log

executable = genus_scabpit.sh
arguments = $(file)
output = ../output/otu_1/genus/bnn_$(Cluster)_$(Process).out
error = ../error/otu_1/genus/bnn_$(Cluster)_$(Process).err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = scabpit.txt,genus_scabpit.sh,../data/otu_1/genus/

requirements = (OpSysMajorVer == 8) && (Machine =!= "e2487.chtc.wisc.edu")
request_cpus = 1
request_memory = 500MB
request_disk = 200GB

queue file from scabpit.txt
