universe = docker
docker_image = xtang75/bnn-software:1
log = ./log/bnn_$(Cluster).log

executable = run_nn.sh
arguments = $(file)
output = ./output/bnn_$(Cluster)_$(Process).out
error = ./error/bnn_$(Cluster)_$(Process).err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = test.txt,run_nn.sh,data/

requirements = (OpSysMajorVer == 8)
request_cpus = 1
request_memory = 4GB
request_disk = 1GB

queue file from test.txt
