universe = docker
docker_image = xtang75/bnn-software:2
log = ./log/order/bnn_$(Cluster)_$(Process).log

executable = order_nn.sh
arguments = $(file)
output = ./output/order/bnn_$(Cluster)_$(Process).out
error = ./error/order/bnn_$(Cluster)_$(Process).err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = filename.txt,order_nn.sh,data/order/

requirements = (OpSysMajorVer == 8) && (Machine =!= "e2487.chtc.wisc.edu")
request_cpus = 1
request_memory = 500MB
request_disk = 150GB

queue file from filename.txt
