universe = docker
docker_image = xtang75/bnn-software:2
log = ./log/family/bnn_$(Cluster)_$(Process).log

executable = family_scabpit.sh
arguments = $(file)
output = ./output/family/bnn_$(Cluster)_$(Process).out
error = ./error/family/bnn_$(Cluster)_$(Process).err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = scabpit.txt,family_scabpit.sh,data/family/

requirements = (OpSysMajorVer == 8) && (Machine =!= "e2487.chtc.wisc.edu")
request_cpus = 1
request_memory = 100MB
request_disk = 30GB

queue file from scabpit.txt
