universe = docker
docker_image = xtang75/bnn-software:2
log = ./log/phylum/bnn_$(Cluster)_$(Process).log

executable = phylum_scabsuper.sh
arguments = $(file)
output = ./output/phylum/bnn_$(Cluster)_$(Process).out
error = ./error/phylum/bnn_$(Cluster)_$(Process).err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = scabsuper.txt,phylum_scabsuper.sh,data/phylum/

requirements = (OpSysMajorVer == 8) && (Machine =!= "e2487.chtc.wisc.edu")
request_cpus = 1
request_memory = 100MB
request_disk = 50GB

queue file from scabsuper.txt
